### ISSUE TITLE
phaser4 request

### ISSUE THREAD

**Issue by akeboshi1** [phaserjs/phaser4#3]
- Whether the stage coordinates and container coordinates can be unified. In actual projects, if some display content is more complicated, it is easy to make errors in calculating the position;
- I regard the scene in phaser3 as a certain layer in the game. There may always be multiple layers in a game. As for his camera, I only use the camera in the currently activated scene in the project, but I like it very much. scene wording, I hope to keep

**Comment by photonstorm** [comment]
Containers are fully implemented and so are multiple Scenes, each with its own Camera. You can track progress in this repo: https://github.com/phaserjs/phaser-nano (feel free to add ideas there)
